[tool.isort]
profile = "black"
line_length = 99
py_version=311
known_third_party = ["polars"]

[tool.black]
line-length = 99
target-version = ['py312']
force-exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
    | migrations
)
'''
